import { useMemo, useState } from "react"
import { Minus, Plus, ShoppingBag, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"

type Product = { id: number; name: string; type: string; category: string; sizes: string[]; colors: { name: string; hex: string; image: string }[] }
const products: Product[] = [
  { id: 1, name: "REMERA REGULAR", type: "ALGODÓN 24.1 / UNISEX", category: "REMERAS", sizes: ["S","M","L","XL","XXL"], colors: [{name:"NEGRO",hex:"#181818",image:"./products/p4-0.png"},{name:"BLANCO",hex:"#f7f7f2",image:"./products/p4-1.png"},{name:"GRIS MELANGE",hex:"#b5b5b0",image:"./products/p4-2.png"}] },
  { id: 2, name: "REMERA OVERSIZE", type: "ALGODÓN 24.1 / UNISEX", category: "REMERAS", sizes: ["S","M","L","XL"], colors: [{name:"NEGRO",hex:"#181818",image:"./products/p11-0.png"},{name:"BLANCO",hex:"#f7f7f2",image:"./products/p11-1.png"}] },
  { id: 3, name: "BUZO REGULAR", type: "FRIZA PREMIUM", category: "BUZOS", sizes: ["S","M","L","XL","XXL"], colors: [{name:"NEGRO",hex:"#181818",image:"./products/p35-0.png"},{name:"AZUL MARINO",hex:"#172d49",image:"./products/p35-1.png"},{name:"GRIS MELANGE",hex:"#b5b5b0",image:"./products/p35-2.png"}] },
  { id: 4, name: "BUZO OVERSIZE", type: "FRIZA PREMIUM", category: "BUZOS", sizes: ["S","M","L","XL"], colors: [{name:"NEGRO",hex:"#181818",image:"./products/p37-0.png"},{name:"NATURAL",hex:"#e5ddd1",image:"./products/p37-1.png"},{name:"BORDO",hex:"#704646",image:"./products/p37-2.png"}] },
  { id: 5, name: "CUELLO REDONDO", type: "FRIZA PREMIUM", category: "BUZOS", sizes: ["S","M","L","XL","XXL"], colors: [{name:"NEGRO",hex:"#181818",image:"./products/p40-0.png"},{name:"NATURAL",hex:"#e5ddd1",image:"./products/p40-1.png"}] },
  { id: 6, name: "CAMPERA DE FRIZA", type: "INVISIBLE PREMIUM", category: "BUZOS", sizes: ["S","M","L","XL","XXL"], colors: [{name:"NEGRO",hex:"#181818",image:"./products/p41-0.png"},{name:"AZUL MARINO",hex:"#172d49",image:"./products/p41-1.png"}] },
]
type CartItem = { product: Product; color: Product["colors"][number]; size: string; quantity: number }

export default function App() {
  const [filter, setFilter] = useState("TODOS"), [selected, setSelected] = useState<Product | null>(null), [cart, setCart] = useState<CartItem[]>([])
  const shown = useMemo(() => filter === "TODOS" ? products : products.filter(p => p.category === filter), [filter])
  const count = cart.reduce((n, item) => n + item.quantity, 0)
  const add = (item: CartItem) => setCart(current => { const found = current.find(x => x.product.id === item.product.id && x.size === item.size && x.color.name === item.color.name); return found ? current.map(x => x === found ? {...x, quantity: x.quantity + item.quantity} : x) : [...current, item] })
  return <main className="min-h-screen bg-stone-100 text-stone-950"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b-2 border-stone-950 bg-stone-100 px-5"><b className="text-3xl font-black">B<span className="text-orange-600">·</span></b><nav className="hidden gap-6 text-xs font-medium md:flex"><a href="#prendas">PRENDAS</a><a href="#proceso">CÓMO COMPRAR</a><a href="#talles">TALLES</a></nav><Cart count={count} cart={cart} setCart={setCart}/></header><section className="grid min-h-[620px] border-b-2 border-stone-950 md:grid-cols-2"><div className="flex flex-col justify-center p-8 md:p-20"><Badge variant="outline" className="w-fit rounded-none">BALANCE TEXTIL / PERSONALIZADOS</Badge><h1 className="mt-6 text-7xl font-black leading-[.86] tracking-tighter md:text-9xl">VESTÍ A TU<br/>EQUIPO.</h1><p className="mt-7 max-w-sm text-sm">Indumentaria personalizada para equipos, empresas y negocios que quieren verse profesionales.</p><Button asChild className="mt-8 w-fit rounded-none"><a href="#prendas">VER PRENDAS ↓</a></Button></div><div className="relative min-h-96 border-t-2 border-stone-950 bg-[url('./catalog/page-2.png')] bg-cover bg-center md:border-l-2 md:border-t-0"><span className="absolute bottom-6 right-6 text-right text-4xl font-black leading-none text-white">HECHO A<br/>MEDIDA</span></div></section><section id="prendas" className="p-5 md:p-12"><div className="flex flex-wrap items-end justify-between gap-4"><h2 className="text-6xl font-black tracking-tighter md:text-8xl">PRENDAS</h2><Badge variant="secondary" className="rounded-full">{shown.length.toString().padStart(2,"0")}</Badge></div><ToggleGroup type="single" value={filter} onValueChange={v => v && setFilter(v)} className="mt-8 flex flex-wrap justify-start">{["TODOS","REMERAS","BUZOS"].map(x=><ToggleGroupItem className="rounded-full border" value={x} key={x}>{x}</ToggleGroupItem>)}</ToggleGroup><div className="mt-8 grid gap-5 md:grid-cols-2">{shown.map(p=><ProductCard key={p.id} product={p} onSelect={()=>setSelected(p)}/>)}</div></section><section id="proceso" className="bg-stone-950 p-8 text-stone-100 md:p-16"><Badge variant="outline" className="rounded-none text-stone-100">ASÍ TRABAJAMOS / 01</Badge><h2 className="mt-6 text-6xl font-black leading-none md:text-8xl">PROCESO<br/>DE COMPRA.</h2><div className="mt-12 grid border-l border-t border-stone-600 md:grid-cols-4">{["ELEGÍ LA PRENDA","ENVIÁ TU IDEA","APROBAMOS","RECIBÍ TU PEDIDO"].map((x,i)=><div className="min-h-44 border-b border-r border-stone-600 p-4" key={x}><small>0{i+1}</small><h3 className="mt-12 text-xl font-bold">{x}</h3></div>)}</div></section><ProductDialog product={selected} onClose={()=>setSelected(null)} onAdd={add}/></main>
}
function ProductCard({product,onSelect}:{product:Product;onSelect:()=>void}) { const [color,setColor]=useState(0); const active=product.colors[color]; return <article className="group border-2 border-stone-950 bg-white"><button className="relative block aspect-[1.18] w-full overflow-hidden bg-stone-200" onClick={onSelect}><img className="h-full w-full object-contain transition duration-500 group-hover:scale-[1.035]" src={active.image} alt={product.name}/><Badge className="absolute left-3 top-3 rounded-none">{active.name}</Badge><Plus className="absolute bottom-3 right-3 rounded-full bg-stone-950 p-1 text-white" size={28}/></button><div className="flex justify-between p-4"><div><small>{product.type}</small><h3 className="text-xl font-bold">{product.name}</h3></div><span className="text-xs">COTIZAR</span></div><div className="flex gap-3 px-4 pb-4">{product.colors.map((c,i)=><button aria-label={c.name} onClick={()=>setColor(i)} key={c.name} className={`h-4 w-4 rounded-full border-2 ${i===color?"border-stone-950 ring-2 ring-stone-950 ring-offset-2":"border-stone-400"}`} style={{background:c.hex}}/>)}</div></article> }
function ProductDialog({product,onClose,onAdd}:{product:Product|null;onClose:()=>void;onAdd:(i:CartItem)=>void}) { const [color,setColor]=useState(0),[size,setSize]=useState(""),[qty,setQty]=useState(1); if(!product)return null; const active=product.colors[color]; return <Dialog open onOpenChange={onClose}><DialogContent className="max-w-3xl rounded-none p-0"><div className="grid md:grid-cols-2"><div className="bg-stone-200"><img className="h-80 w-full object-contain md:h-full" src={active.image} alt=""/></div><div className="p-6"><DialogHeader><DialogTitle className="text-3xl font-black">{product.name}</DialogTitle></DialogHeader><p className="mt-2 text-xs">{product.type} · PRESUPUESTO SEGÚN CANTIDAD Y ESTAMPA</p><p className="mt-7 text-xs font-bold">COLOR</p><ToggleGroup type="single" value={String(color)} onValueChange={v=>v&&setColor(+v)} className="mt-2 justify-start">{product.colors.map((c,i)=><ToggleGroupItem key={c.name} value={String(i)}>{c.name}</ToggleGroupItem>)}</ToggleGroup><p className="mt-6 text-xs font-bold">TALLE</p><ToggleGroup type="single" value={size} onValueChange={setSize} className="mt-2 justify-start">{product.sizes.map(s=><ToggleGroupItem key={s} value={s}>{s}</ToggleGroupItem>)}</ToggleGroup><div className="mt-7 flex items-center justify-between"><b className="text-xs">CANTIDAD</b><div className="flex items-center border"><Button variant="ghost" size="icon" onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></Button><span className="grid w-9 place-items-center text-sm font-bold">{qty}</span><Button variant="ghost" size="icon" onClick={()=>setQty(qty+1)}><Plus/></Button></div></div><Button disabled={!size} className="mt-7 w-full rounded-none" onClick={()=>{onAdd({product,color:active,size,quantity:qty});onClose()}}>SUMAR {qty} AL PEDIDO</Button></div></div></DialogContent></Dialog> }
function Cart({count,cart,setCart}:{count:number;cart:CartItem[];setCart:React.Dispatch<React.SetStateAction<CartItem[]>>}) { return <Sheet><SheetTrigger asChild><Button variant="outline" className="rounded-full text-xs"><ShoppingBag/> PEDIDO <b>{count}</b></Button></SheetTrigger><SheetContent className="w-full sm:max-w-md"><SheetHeader><SheetTitle>TU PEDIDO / {count}</SheetTitle></SheetHeader><div className="mt-8 space-y-4">{cart.length?cart.map((x,i)=><div className="flex gap-3 border-b pb-4" key={i}><img className="h-20 w-16 bg-stone-100 object-contain" src={x.color.image}/><div className="flex-1 text-xs"><b className="block">{x.product.name}</b><span>{x.color.name} / {x.size}</span><div className="mt-3 flex items-center gap-3"><Button size="icon" variant="outline" onClick={()=>setCart(c=>c.map((z,n)=>n===i?{...z,quantity:Math.max(1,z.quantity-1)}:z))}><Minus/></Button><b>{x.quantity}</b><Button size="icon" variant="outline" onClick={()=>setCart(c=>c.map((z,n)=>n===i?{...z,quantity:z.quantity+1}:z))}><Plus/></Button></div></div><Button size="icon" variant="ghost" onClick={()=>setCart(c=>c.filter((_,n)=>n!==i))}><X/></Button></div>):<p className="text-sm text-muted-foreground">TU PEDIDO ESTÁ VACÍO.</p>}</div><Button className="mt-8 w-full rounded-none" disabled={!cart.length} onClick={()=>window.open("https://wa.me/5422622319015","_blank")}>CONTINUAR POR WHATSAPP</Button></SheetContent></Sheet> }
